#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin; adapted to official @deepseek-ai/* imports.
# Build: compile src/ -> lib/ with a local tsc or a dsh source checkout's tsc.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Locate DSH source checkout (optional). Env var wins, then common paths.
CHECKOUT="${DSH_CHECKOUT:-}"
if [ -z "$CHECKOUT" ]; then
  for candidate in "$HOME/dsh-harness" "$HOME/dsh" "$HOME/.dsh/dsh-harness"; do
    if [ -d "$candidate/packages" ]; then CHECKOUT="$candidate"; break; fi
  done
fi

MIRROR=""
if [ -n "$CHECKOUT" ] && [ -d "$CHECKOUT/packages" ]; then
  echo "=== Source checkout mode: $CHECKOUT ==="
  MIRROR=""
else
  # Fallback: use the installed DSH profile dependency mirror (compiled packages).
  MIRROR="${DSH_PROFILE_NODE_MODULES:-$HOME/.dsh/profiles/node_modules}"
  if [ ! -d "$MIRROR/@deepseek-ai" ]; then
    echo "build: cannot locate dsh source checkout or dependency mirror (set DSH_CHECKOUT or DSH_PROFILE_NODE_MODULES)" >&2
    exit 1
  fi
  CHECKOUT=""
  echo "=== Dependency mirror mode: $MIRROR ==="
fi

# Locate tsc: local installed TypeScript first, then the source checkout's tsc.
if [ -x "node_modules/.bin/tsc" ] || [ -f "node_modules/.bin/tsc.cmd" ]; then
  TSC="node_modules/.bin/tsc"
elif [ -n "$CHECKOUT" ] && { [ -x "$CHECKOUT/node_modules/.bin/tsc" ] || [ -f "$CHECKOUT/node_modules/.bin/tsc.cmd" ]; }; then
  TSC="$CHECKOUT/node_modules/.bin/tsc"
else
  echo "build: tsc not found; run 'npm install' (typescript) first or set DSH_CHECKOUT" >&2
  exit 1
fi

link_pkg() {
  local link="$1" target="$2"
  node -e "
    const fs = require('fs');
    const path = require('path');
    const link = path.resolve(process.argv[1]);
    const target = path.resolve(process.argv[2]);
    fs.rmSync(link, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(link), { recursive: true });
    fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
  " "$link" "$target"
}

echo "=== Linking build dependencies ==="
if [ -n "$MIRROR" ]; then
  # The installed profile mirror already contains all @deepseek-ai/*, @standard-schema, @types packages.
  rm -rf node_modules/@deepseek-ai node_modules/@types node_modules/@standard-schema
  mkdir -p node_modules
  link_pkg node_modules/@deepseek-ai "$MIRROR/@deepseek-ai"
  link_pkg node_modules/@types "$MIRROR/@types"
  link_pkg node_modules/@standard-schema "$MIRROR/@standard-schema"
else
  mkdir -p node_modules/@deepseek-ai
  link_pkg node_modules/@deepseek-ai/cordis "$CHECKOUT/vendor/cordis"
  link_pkg node_modules/@deepseek-ai/cosmokit "$CHECKOUT/vendor/cosmokit"
  link_pkg node_modules/@deepseek-ai/schemastery "$CHECKOUT/vendor/schemastery"
  link_pkg node_modules/@deepseek-ai/dsh-tools "$CHECKOUT/packages/core/tools"
  link_pkg node_modules/@deepseek-ai/dsh-llm "$CHECKOUT/packages/llm/llm"
  link_pkg node_modules/@deepseek-ai/dsh-system-prompt "$CHECKOUT/packages/core/system-prompt"
  link_pkg node_modules/@types/node "$CHECKOUT/node_modules/@types/node"
  STD_SCHEMA=$(find "$CHECKOUT/node_modules/.pnpm" -maxdepth 1 -type d -iname '@standard-schema+spec@*' 2>/dev/null | head -1)
  if [ -n "$STD_SCHEMA" ]; then
    rm -rf node_modules/@standard-schema
    mkdir -p node_modules/@standard-schema
    link_pkg node_modules/@standard-schema/spec "$STD_SCHEMA/node_modules/@standard-schema/spec"
  fi
fi

echo "=== Compiling src -> lib ==="
"$TSC" -p tsconfig.json
echo "=== Build complete ==="